apiVersion: opg.ewbi.katalis.com/v1beta1
kind: ApplicationDeployment
metadata:
  labels:
    app.kubernetes.io/name: opg-ewbi-crds
    app.kubernetes.io/managed-by: kustomize
  name: applicationdeployment-sample
  namespace: guest
spec:
  federationContextId: f27e71c7-e701-27f2-59b6-bf2de514ce02
  appId: "EdgeAppTester01"
  appInstanceId: "instance_1118b447_5685_4c13_a0e2_c4f46c271865"
  zoneId: "b0b071c7-e701-27f2-59b6-bf2de514ce06"
  appProviderId: "TheAmazingTestingCompany"
  appDetails:
    appVersion: "1.0.0"
    zoneInfo:
      flavourId: m1.tiny
      resourceConsumption: RESERVED_RES_SHALL
      resPool: "2gEHwMSD"
    appInstCallbackLink: 192.168.42.12:6443
status:
  accessPointInfo:
    - interfaceId: 8390b1e4-4a47-49f2-8c10-85f8c679a957
      accessPoints: {
        port: 3000,
        fqdn: amazingtest.theamazingtestingcompany.com,
        ipv4Addresses: [ "10.0.0.12", "10.0.1.12"],
        ipv6Addresses: ["2001:db8:85a3::8a2e:370:7334", "2001:db8:85a3::8a2a:370:7334"]
      }
  appInstanceInfo:
    - appInstIdentifier: "b0b071c7-e701-27f2-59b6-bf2de514ce06"
      appInstanceState: "PENDING"
